micronaut:
  application:
    name: auth_jwt
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"testSecret"'
    server:
    cors:
      enabled: true
      configurations:
        allowedHeaders:
          - Content-Type
        allowedMethods:
          - GET
          - POST
          - DELETE
        allowedOrigins:
          - http://localhost:3000
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/worktest
    username: postgres
    password: Roxy1993!!!
    driverClassName: org.postgresql.Driver
netty:
  default:
    allocator:
      max-order: 3
